type Query {
    books: [Book!]!
    bookById(id: ID!): Book
    authors: [Author!]!
    authorById(id: ID!): Author
}

type Mutation {
    addBook(input: BookInput!): Book!
    updateStock(id: ID!, stock: Int!): Book!
}

type Book {
    id: ID!
    title: String!
    pages: Int!
    price: Float!
    stock: Int!
    author: Author
}

type Author {
    id: ID!
    name: String!
    country: String!
}

input BookInput {
    title: String!
    pages: Int!
    price: Float!
    stock: Int!
    authorId: ID!
}
