type Query {
    books(filter: BookFilter, sort: BookSort, limit: Int, offset: Int): [Book!]!
    bookCount(filter: BookFilter): Int!
    bookById(id: ID!): Book
    authors: [Author!]!
    authorById(id: ID!): Author
}

type Mutation {
    addBook(input: BookInput!): Book!
    updateStock(id: ID!, stock: Int!): Book!
}

type Book {
    id: ID!
    title: String!
    pages: Int!
    price: Float!
    stock: Int!
    author: Author
}

type Author {
    id: ID!
    name: String!
    country: String!
}

input BookInput {
    title: String!
    pages: Int!
    price: Float!
    stock: Int!
    authorId: ID!
}

input BookFilter {
    titleContains: String
    authorId: ID
    minPrice: Float
    maxPrice: Float
    inStock: Boolean
}

enum BookSort {
    TITLE_ASC
    TITLE_DESC
    PRICE_ASC
    PRICE_DESC
    STOCK_ASC
    STOCK_DESC
}
